version: '3'
services:
  destination_postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: destination_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Auto-creates tables
    networks:
      - elt-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  elt-network:
    driver: bridge

#  elt_script:
#    build:
#      context: ./elt_script
#      dockerfile: Dockerfile
#    command: ["python", "main.py"]
#    networks:
#      - elt-network
#    depends_on:
#      destination_postgres:
#        condition: service_healthy